.TH "vectoroids" "6" "v1.1.0 - 2002.04.20" "Bill Kendrick" "Games"
.SH "NAME"
.LP 
vectoroids \- A vector-based asteroid\-shooting game written in libSDL.
.SH "SYNTAX"
.LP 
vectoroids [\fIoptions\fP]
.SH "DESCRIPTION"
.LP 
Use the \fBleft\fR and \fBright\fR keys (or joystick) to rotate your ship.
Use the \fBup\fR key (joystick \fBfire\-A\fR) to thrust,
and \fBspace\fR (or joystick \fBfire\-B\fR) to fire bullets.
.br
Destroy all of the asteroids to progress to the next level.
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-nosound\fR
Disables sound and music.
.TP
\fB\-\-fullscreen\fR
Runs in fullscreen mode, if possible.
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.TP
\fB\-\-usage\fR
Displays acceptable command\-line options.
.TP
\fB\-\-copying\fR
Displays copying information.
.SH "FILES"
\fI/usr/local/share/vectoroids/\fP \- Sound, music and graphics data.
.TP
\fI~/.vectoroidsrc\fP \- Paused game state and high score data.
.LP 
.SH "AUTHORS"
.LP 
Bill Kendrick <bill@newbreedsoftware.com> \- Programming
.br
Mike Faltiss <deadchannel@hotmail.com> \- Music
.LP
See "README.txt" and "CHANGES.txt" for full credits.
