/*********************************************************************
 * 
 *  PSP Media Center main startup file
 *  adresd 2005
 */
#include <pspkernel.h>
#include <pspdebug.h>
#include <pspiofilemgr.h>
#include <pspctrl.h>
#include <pspaudio.h>
#include <pspdisplay.h>
#include <stdlib.h>
#include <string.h>
#include <pspmoduleinfo.h>
#include <pspaudiolib.h>
#include <pspmodulemgr.h>
#include <pspsdk.h>

#include "codec.h"

//  These are the headers for the different codecs
//  auto-generated by the makefile
#include "codecincs.h"

/* Define the module info section */
#define K_STARTUP
#define ENABLE_SIO

#ifdef K_STARTUP
PSP_MODULE_INFO("PSPMC", 0x1000, 1, 1);
PSP_MAIN_THREAD_ATTR(THREAD_ATTR_USER);
#else
PSP_MODULE_INFO("PSPMC", 0x1000, 1, 1);
PSP_MAIN_THREAD_ATTR(0);
#endif

/* Define printf, just to make typing easier */
#define printf  pspDebugScreenPrintf

codecStubs stubs[100];
codecStubs *decoder;
unsigned char banner[] = "PSP Media Center v0.91 by John_K & adresd\0";
int codecnum = 0;

/**
 * custom exception handler
 */
void MyExceptionHandler(PspDebugRegBlock * regs)
{
    /* I always felt BSODs were more interesting that white on black */
    pspDebugScreenSetBackColor(0x00FF0000);
    pspDebugScreenSetTextColor(0xFFFFFFFF);
    //pspDebugScreenClear();

    pspDebugScreenSetXY(0, 17);
    pspDebugScreenPrintf("\nI regret to inform you your psp has just crashed\n");
    pspDebugScreenPrintf("Exception Details:\n");
    pspDebugDumpException(regs);
    pspDebugScreenSetBackColor(0x00000000);
}

//Put this here so we can dump our own stuff
static const char *codeTxt[32] = 
{
    "Interrupt", "TLB modification", "TLB load/inst fetch", "TLB store",
    "Address load/inst fetch", "Address store", "Bus error (instr)", 
    "Bus error (data)", "Syscall", "Breakpoint", "Reserved instruction", 
    "Coprocessor unusable", "Arithmetic overflow", "Unknown 14",
	"Unknown 15", "Unknown 16", "Unknown 17", "Unknown 18", "Unknown 19",
	"Unknown 20", "Unknown 21", "Unknown 22", "Unknown 23", "Unknown 24",
	"Unknown 25", "Unknown 26", "Unknown 27", "Unknown 28", "Unknown 29",
	"Unknown 31"
};
static const unsigned char regName[32][5] =
{
    "zr", "at", "v0", "v1", "a0", "a1", "a2", "a3",
    "t0", "t1", "t2", "t3", "t4", "t5", "t6", "t7", 
    "s0", "s1", "s2", "s3", "s4", "s5", "s6", "s7",
    "t8", "t9", "k0", "k1", "gp", "sp", "fp", "ra"
};

void MySioExceptionHandler(PspDebugRegBlock * regs)
{
    int i;
    fprintf(stdout, "Your PSP has just crashed!\r\n");
    fprintf(stdout, "Exception details:\r\n");
    

    fprintf(stdout, "Exception - %s\r\n", codeTxt[(regs->cause >> 2) & 31]);
    fprintf(stdout, "EPC       - %08X\r\n", regs->epc);
    fprintf(stdout, "Cause     - %08X\r\n", regs->cause);
    fprintf(stdout, "Status    - %08X\r\n", regs->status);
    fprintf(stdout, "BadVAddr  - %08X\r\n", regs->badvaddr);
    for(i = 0; i < 32; i+=4)
    {
	fprintf(stdout, "%s:%08X %s:%08X %s:%08X %s:%08X\r\n", regName[i], regs->r[i], regName[i+1], regs->r[i+1], regName[i+2], regs->r[i+2], regName[i+3], regs->r[i+3]);
    }
    fprintf(stdout, "Please restart your PSP now.\r\n");
}

#ifdef K_STARTUP		// causes problems, so done in main at the moment
/**
 * Function that is called from _init in kernelmode before the
 * main thread is started in usermode.
 */
__attribute__ ((constructor))
void loaderInit()
{
    pspKernelSetKernelPC();
    pspSdkInstallNoDeviceCheckPatch();
#ifdef ENABLE_SIO
    pspDebugSioSetBaud(115200);
    pspDebugSioInit();
    pspDebugInstallStdoutHandler(pspDebugSioPutData);
    pspDebugInstallStderrHandler(pspDebugSioPutData);
    pspDebugSioInstallKprintf();
    pspDebugInstallErrorHandler(MySioExceptionHandler);
#else
    pspDebugInstallKprintfHandler(NULL);
    pspDebugInstallErrorHandler(MyExceptionHandler);
#endif
    
}
#endif


/* Exit callback */
int exit_callback(int arg1, int arg2, void *common)
{
    pspAudioEnd();
    sceKernelExitGame();
}

/* Callback thread */
int CallbackThread(SceSize args, void *argp)
{
    int cbid;
    cbid = sceKernelCreateCallback("Exit Callback", exit_callback, NULL);
    sceKernelRegisterExitCallback(cbid);
    sceKernelSleepThreadCB();
}

/* Sets up the callback thread and returns its thread id */
int SetupCallbacks(void)
{
    int thid = 0;
    thid = sceKernelCreateThread("update_thread", CallbackThread, 0x11, 0xFA0, THREAD_ATTR_USER, 0);
    if (thid >= 0)
	sceKernelStartThread(thid, 0, 0);
    return thid;
}

/**
 *  main routine 
 */
int main(int argc, char *argv[])
{
    int stubnum;
#ifndef K_STARTUP
    pspSdkInstallNoDeviceCheckPatch();
    pspDebugInstallKprintfHandler(NULL);
    pspDebugInstallErrorHandler(MyExceptionHandler);
#endif
    SetupCallbacks();
    // Setup Pad
    sceCtrlSetSamplingCycle(0);
    sceCtrlSetSamplingMode(0);

    //get codecStubs
    stubnum = 0;
    CODEC_INITSTUBS codecnum = stubnum;

    pspAudioInit();

    // This is where we call the gui
    gui_main();

    pspAudioEnd();
    
    sceKernelExitGame();

    // wait forever
    sceKernelSleepThread();
    return 0;
}
