/*********************************************************************
 * 
 *  PSPMC as a Library, for other programs to use
 *  adresd 2005
 */
#include <pspkernel.h>
#include <pspdebug.h>
#include <pspiofilemgr.h>
#include <pspctrl.h>
#include <pspaudio.h>
#include <pspdisplay.h>
#include <stdlib.h>
#include <string.h>
#include <pspmoduleinfo.h>
#include <pspaudiolib.h>
#include <pspusb.h>
#include <pspusbstor.h>
#include <pspmodulemgr.h>
#include <pspsdk.h>


#include "../../codec.h"

//  These are the headers for the different codecs
//  auto-generated by the makefile
#include "../../codecincs.h"

#include "libpspmc.h"

/* Define printf, just to make typing easier */
#define printf  pspDebugScreenPrintf

codecStubs stubs[100];
codecStubs *decoder;
int codecnum = 0;


/**
 *  main routine 
 */
int libpspmc_init()
{
  int stubnum;
  //get codecStubs
  stubnum = 0;
  CODEC_INITSTUBS codecnum = stubnum;

  pspAudioInit();
  decoder = 0;
  return 1;
}
int libpspmc_end()
{
  pspAudioEnd();
  return 1;
}

int libpspmc_stop()
{
  if (decoder != 0) {
	  decoder->stop();
	  decoder->end();
    decoder = 0;
    return 1;
  }
  return 0;
}


int libpspmc_loadplay(char *filepath)
{
  char filename[200];
  int codec;
  int finished = 0;

  if (decoder != 0)
    libpspmc_stop();  // stop previous tune first

  //determine codec of the file
  for (codec = 0; codec <= codecnum; codec++) {
  	char *ptr = &(stubs[codec].extension[0]);
  	while (*ptr != 0) {
	    if (strncasecmp(&filepath[strlen(filepath) - 3], ptr, 3) == 0) {
	    	decoder = &stubs[codec];
		    break;
	    }
	    ptr += 4;
	  }
  }

  if (decoder != 0) {
    decoder->init(0);
    if (decoder->load(filepath)) {
      decoder->play();
      return 1;
    }
  }
  return 0;
}


int libpspmc_geteos()
{
  if (decoder == 0)
    return 1;
  else
    return decoder->eos();
}

int libpspmc_getinfo(unsigned char *string)
{
  return 0;
}

int libpspmc_gettime(unsigned char *string)
{
  if (decoder != 0) {
    decoder->time(string);
    return 1;
  }
  return 0;
}

